### Criar uma nova tarefa
POST http://localhost:3000/tarefas
Content-Type: application/json

{
    "titulo": "Meditação Guiada",
    "descricao": "Fazer uma sessão de meditação guiada de 15 minutos.",
    "status": "em_progresso"
}

### Listar todas as tarefas (com busca opcional)
GET http://localhost:3000/tarefas

### Atualizar uma tarefa existente
PUT http://localhost:3000/tarefas/1
Content-Type: application/json

{
    "titulo": "Estudar Node.js e PostgreSQL",
    "descricao": "Revisar conceitos avançados de Node.js e PostgreSQL.",
    "status": "em_progresso"
}

### Deletar uma tarefa
DELETE http://localhost:3000/tarefas/1